### ISSUE TITLE
using podman dev container fails with  E: Unable to locate package azure-functions-core-tools-4

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [Azure-Samples/azure-sql-db-session-recommender-v2#3]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Using podman rootful or rootless or docker with repo cloned on Windows 11 

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 11 23H2 22631.3235
PODMAN

### Versions
>

### Mention any other details that might be useful

```
ERROR [dev_container_auto_added_stage_label 2/2] RUN curl https://packages.microsoft.com/keys/microsoft.a  35.5s
------
 > [dev_container_auto_added_stage_label 2/2] RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dear
mor > microsoft.gpg     && mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg     && sh -c 'echo "deb [arch=amd64]
 https://packages.microsoft.com/debian/$(lsb_release -rs | cut -d'.' -f 1)/prod $(lsb_release -cs) main" > /etc/apt/s
o`urces.list.d/dotnetdev.list'     && apt-get update && apt-get install -y azure-functions-core-tools-4     && apt-get
 clean -y && rm -rf /var/lib/apt/lists/*:
0.260   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
0.260                                  Dload  Upload   Total   Spent    Left  Speed
100   983  100   983    0     0    397      0  0:00:02  0:00:02 --:--:--   397
3.002 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
3.074 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
3.102 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
3.286 Get:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8068 kB]
3.765 Get:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [269 kB]
3.781 Get:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [18.8 kB]
6.561 Get:7 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
6.684 Get:8 https://dl.yarnpkg.com/debian stable/main all Packages [10.9 kB]
6.720 Get:9 https://dl.yarnpkg.com/debian stable/main amd64 Packages [10.9 kB]
33.00 Err:10 https://packages.microsoft.com/debian/11/prod bullseye InRelease
33.00   Could not wait for server fd - select (11: Resource temporarily unavailable) [IP: 13.107.213.64 443]
33.02 Fetched 8603 kB in 30s (286 kB/s)
33.02 Reading package lists...
33.89 W: Failed to fetch https://packages.microsoft.com/debian/11/prod/dists/bullseye/InRelease  Could not wait for s
erver fd - select (11: Resource temporarily unavailable) [IP: 13.107.213.64 443]
33.89 W: Some index files failed to download. They have been ignored, or old ones used instead.
33.92 Reading package lists...
34.67 Building dependency tree...
34.97 Reading state information...
35.44 E: Unable to locate package azure-functions-core-tools-4
------
Dockerfile-with-features:5
--------------------
   4 |     FROM --platform=amd64 mcr.microsoft.com/devcontainers/${IMAGE} AS dev_container_auto_added_stage_label
   5 | >>> RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg \
   6 | >>>     && mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg \
   7 | >>>     && sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/debian/$(lsb_release -rs | cut -d'.' -
f 1)/prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list' \
   8 | >>>     && apt-get update && apt-get install -y azure-functions-core-tools-4 \
   9 | >>>     && apt-get clean -y && rm -rf /var/lib/apt/lists/*
  10 |
--------------------
ERROR: failed to solve: process "/bin/sh -c curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor >
microsoft.gpg     && mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg     && sh -c 'echo \"deb [arch=amd64] http
s://packages.microsoft.com/debian/$(lsb_release -rs | cut -d'.' -f 1)/prod $(lsb_release -cs) main\" > /etc/apt/sourc
es.list.d/dotnetdev.list'     && apt-get update && apt-get install -y azure-functions-core-tools-4     && apt-get cle
an -y && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100
[878241 ms] Error: Command failed: docker buildx build --load --build-arg BUILDKIT_INLINE_CACHE=1 -f C:\\AppData\Local\Temp\devcontainercli\container-features\0.56.2-1710777329920\Dockerfile-with-features -t vsc-azure-sql-db-session-recommender-v2-c360c9271e01c7daa29b5aa1e8d317eeae8192529bdd0c1a8ae3a4c7efeddb11 --target dev_containers_target_stage --build-arg IMAGE=dotnet:7.0-bullseye --build-context dev_containers_feature_content_source=C:\\AppData\Local\Temp\devcontainercli\container-features\0.56.2-1710777329920 --build-arg _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label --build-arg _DEV_CONTAINERS_IMAGE_USER=root --build-arg _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp c:\\OneDrive\Documents\GitHub\ClonedForked\azure-sql-db-session-recommender-v2\.devcontainer
[878242 ms]     at BtA (\.vscode\extensions\ms-vscode-remote.remote-containers-0.348.0\dist\spec-node\devContainersSpecCLI.js:465:1933)
[878242 ms]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[878242 ms]     at async K0 (\.vscode\extensions\ms-vscode-remote.remote-containers-0.348.0\dist\spec-node\devContainersSpecCLI.js:464:1841)
[878242 ms]     at async yH (\.vscode\extensions\ms-vscode-remote.remote-containers-0.348.0\dist\spec-node\devContainersSpecCLI.js:464:610)
[878242 ms]     at async StA (\.vscode\extensions\ms-vscode-remote.remote-containers-0.348.0\dist\spec-node\devContainersSpecCLI.js:481:3660)
[878243 ms]     at async ZC (\.vscode\extensions\ms-vscode-remote.remote-containers-0.348.0\dist\spec-node\devContainersSpecCLI.js:481:4775)
[878243 ms]     at async trA (\.vscode\extensions\ms-vscode-remote.remote-containers-0.348.0\dist\spec-node\devContainersSpecCLI.js:614:11269)
[878243 ms]     at async erA (\.vscode\extensions\ms-vscode-remote.remote-containers-0.348.0\dist\spec-node\devContainersSpecCLI.js:614:11010)
[878310 ms] Exit code 1
[878326 ms] Command failed: C:\Program Files\Microsoft VS Code\Code.exe \.vscode\extensions\ms-vscode-remote.remote-containers-0.348.0\dist\spec-node\devContainersSpecCLI.js up --user-data-folder AppData\Roaming\Code\User\globalStorage\ms-vscode-remote.remote-containers\data --container-session-data-folder /tmp/devcontainers-9763582c-9822-48a9-8d59-855913d3e22a1710776938680 --workspace-folder redacted\azure-sql-db-session-recommender-v2 --workspace-mount-consistency cached --id-label devcontainer.local_folder=redact3ed\azure-sql-db-session-recommender-v2 --id-label devcontainer.config_file=redactedazure-sql-db-session-recommender-v2\.devcontainer\devcontainer.json --log-level debug --log-format json --config REDACTEDClonedForked\azure-sql-db-session-recommender-v2\.devcontainer\devcontainer.json --default-user-env-probe loginInteractiveShell --mount type=volume,source=vscode,target=/vscode,external=true --mount type=bind,source=\\wsl.localhost\Ubuntu\mnt\wslg\runtime-dir\wayland-0,target=/tmp/vscode-wayland-ede0854e-023c-4954-bfb5-d9b42db9c71a.sock --skip-post-create --update-remote-user-uid-default on --mount-workspace-git-root --terminal-columns 117 --terminal-rows 21
[878326 ms] Exit code 1
```

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by yorek** [comment]
I don't have podman, but now I'm using npm to install function tools, let me know if it works now
